[tls]

[tls.stores]

[tls.stores.default]

[tls.stores.default.defaultCertificate]
certFile = "/run/secrets/cert"
keyFile = "/run/secrets/cert-key"

[[tls.certificates]]
certFile = "/run/secrets/cert"
keyFile = "/run/secrets/cert-key"
stores = ["default"]