ARG SOURCE_IMAGE
FROM ${SOURCE_IMAGE}

RUN apk --no-cache add git

RUN go get -u github.com/FiloSottile/mkcert

RUN mkdir -p /certs

WORKDIR /certs

ENV CAROOT=/tmp

RUN echo "mkcert -install" > /entrypoint.sh \
    && echo 'cp "$(mkcert -CAROOT)/rootCA.pem" ./' >> /entrypoint.sh \
    && echo 'mkcert -cert-file cert.pem -key-file cert-key.pem ${1} "*.${1}"' >> /entrypoint.sh

ENTRYPOINT [ "/bin/sh", "/entrypoint.sh" ]

CMD [ "clevrdev.com" ]
