---
version: "3.3"

#
# docker-compose -f image/docker-compose.build.yml build
#

services:
  traefik:
    image: ${TRAEFIK_IMAGE}
    build:
      dockerfile: Dockerfile.traefik
      context: .
      args:
        SOURCE_IMAGE: traefik:v2.3.6

  mkcert:
    image: ${MKCERT_IMAGE}
    build:
      dockerfile: Dockerfile.mkcert
      context: .
      args:
        SOURCE_IMAGE: golang:1.12-alpine
